README.md

Updated readme file with client/server instructions

---

.lfsconfig

Updating the .lfsconfig instructions to match those in o3de main repo
Signed-off-by: AMZN-alexpete <26804013+AMZN-alexpete@users.noreply.github.com>

Updating .lfsconfig comments only

---

Gem/Code/Source/Components/NetworkHitVolumesComponent.cpp
Gem/Code/Source/Components/NetworkRigidBodyComponent.cpp

This change works with core MP changes in https://github.com/o3de/o3de/pull/2146

Update SyncRewind usages to interpolate in MP Sample

---

Gem/Code/Source/Components/NetworkAnimationComponent.cpp
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp
Gem/Code/Source/Components/WasdPlayerMovementComponent.cpp

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4267?view=msvc-160

Fix for w4267 ('var' : conversion from 'size_t' to 'type', possible loss of data)

---

Gem/Code/Source/AutoGen/NetworkHealthComponent.AutoComponent.xml
Gem/Code/Source/AutoGen/NetworkRandomComponent.AutoComponent.xml
Gem/Code/Source/Components/NetworkHealthComponent.cpp
Gem/Code/Source/Components/NetworkHealthComponent.h
Gem/Code/Source/Components/NetworkRandomComponent.cpp
Gem/Code/Source/Components/NetworkRandomComponent.h
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp
Gem/Code/multiplayersample_files.cmake

First cut of a Networked Health Component. Looking at weapons, there are points (that look to be WIP) where you could grab this component and use a mix of Get/SetHealth to update values. I went with authoritative vs autonomous since that seems to be how weapons are setup.

Add NetworkedHealthComponent and NetworkRandomComponent

---

Gem/Code/Source/Components/NetworkHitVolumesComponent.cpp
Gem/Code/Source/Weapons/SceneQuery.cpp
Gem/Code/Source/Weapons/SceneQuery.h
Gem/Code/Source/Weapons/WeaponGathers.cpp
Gem/Code/Source/Weapons/WeaponGathers.h
Gem/Code/Source/Weapons/WeaponTypes.cpp
Gem/Code/Source/Weapons/WeaponTypes.h
Gem/Code/multiplayersample_files.cmake

Signed-off-by: pereslav <pereslav@amazon.com>

Added support for physics scene queries in the weapon system

---

Gem/Code/Source/AutoGen/NetworkWeaponsComponent.AutoComponent.xml
Gem/Code/Source/Components/NetworkAnimationComponent.h
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp
Gem/Code/Source/Components/NetworkWeaponsComponent.h
Gem/Code/Source/Components/WasdPlayerMovementComponent.cpp
Gem/Code/Source/Weapons/BaseWeapon.cpp
Gem/Code/Source/Weapons/IWeapon.h
Gem/Code/Source/Weapons/ProjectileWeapon.cpp
Gem/Code/Source/Weapons/ProjectileWeapon.h
Gem/Code/Source/Weapons/SceneQuery.cpp
Gem/Code/Source/Weapons/TraceWeapon.cpp
Gem/Code/Source/Weapons/TraceWeapon.h
Gem/Code/Source/Weapons/WeaponTypes.cpp
Levels/SampleBase/SampleBase.prefab
Prefabs/Player.prefab

Weapons are now reasonably functional

Multiplayer weapons

---

Gem/Code/Source/Components/NetworkAnimationComponent.cpp
Gem/Code/Source/Components/NetworkAnimationComponent.h

Update NetworkAnimationComponent pre render hooks

---

Scripts/build/Jenkins/Jenkinsfile

- Mimicking https://github.com/o3de/o3de-netsoaktest/blob/development/Scripts/build/Jenkins/Jenkinsfile

Added jenkinsfile

---

Gem/Code/Source/Components/NetworkPlayerMovementComponent.h
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp
Gem/Code/Source/Components/NetworkWeaponsComponent.h

- Verified that Editor and MultiplayerSample server target compiles on Linux
Signed-off-by: Olex Lozitskiy <5432499+AMZN-Olex@users.noreply.github.com>

Linux compilation fixes

---

Gem/Code/Source/Components/NetworkPlayerMovementComponent.h
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp
Gem/Code/Source/Components/NetworkWeaponsComponent.h

Fixes were already verified in stab/2110. This one is just a merge over.
https://github.com/o3de/o3de-multiplayersample/pull/74

Linux fixes for o3de-multiplayersample from stab/2110 to dev branch

---

Gem/Code/Source/Components/NetworkStressTestComponent.cpp

Fix for the release build of o3de-multiplayersample

---

README_LINUX.md

Signed-off-by: Olex Lozitskiy <5432499+AMZN-Olex@users.noreply.github.com>

Added Linux readme

---

Gem/Code/Source/AutoGen/NetworkAiComponent.AutoComponent.xml
Gem/Code/Source/AutoGen/NetworkPlayerMovementComponent.AutoComponent.xml
Gem/Code/Source/AutoGen/NetworkWeaponsComponent.AutoComponent.xml
Gem/Code/Source/Components/NetworkAiComponent.cpp
Gem/Code/Source/Components/NetworkPlayerMovementComponent.cpp
Gem/Code/Source/Components/NetworkPlayerMovementComponent.h
Gem/Code/Source/Components/NetworkStressTestComponent.cpp
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp
InputBindings/player.inputbindings

Changes to allow for better (safer) controller access, especially in situations where entities may be migrating between hosts

Controller fixes

---

scriptcanvas/SpawnIfAuthority.scriptcanvas

Resaving SpawnIfAuthority script canvas. No edits, but the resave fixes an issue and allows the cube/sphere prefab to be spawned. Validated the spheres exist on server, but are filtered out on clients

SpawnIfAuthority Scriptcanvas Fix

---

README.md

Signed-off-by: Pip Potter <61438964+lmbr-pip@users.noreply.github.com>

Add links to the play-in-editor guide and linux setup

---

README_LINUX.md
Scripts/build/Jenkins/Jenkinsfile

- also bringing in Jenkinsfile

Merging over linux readme and jenkins changes to stab/2110 from dev

---

scriptcanvas/SpawnIfAuthority.scriptcanvas

Merging stabilization/2110 up to and including commit c3dacb1 to development
There were no merge conflicts

Merge stabilization/2110

---

README.md
client.cfg
server.cfg

From development branch to stabilization/2110.

Merged over client.cfg/server.cfg and related docs.

---

README.md
client.cfg
server.cfg

Merged over client.cfg/server.cfg and related docs, from dev to stab/2110

---

CMakeLists.txt
cmake/CompilerSettings.cmake
cmake/EngineFinder.cmake
cmake/Platform/Linux/CompilerSettings_linux.cmake

Closes Issue #97
Signed-off-by: Esteban Papp <81431996+amznestebanpapp@users.noreply.github.com>

Adapts to new template

---

Gem/Code/Source/Components/NetworkStressTestComponent.cpp

AI spawner fix, marking entities autonomous

---

Levels/SampleBase/SampleBase.prefab

Added a direction light to solve current lighting issue

---

Levels/SampleBase/SampleBase.prefab

Added skyboxes

---

.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/feature_template.md

Port the O3DE bug and feature templates for repro.

Add basic issue templates for bugs and features

---

Gem/gem.json

Otherwise cmake throws:
```
1>CMake Error at cmake/O3DEJson.cmake:54 (message):
1>  Error reading field at key gem_name in file
1>  "C:/git/o3de-multiplayersample/Gem/gem.json" : member 'gem_name' not found
```

Added gem_name as per new gem definition requirements

---

README.md
README_LINUX.md

Signed-off-by: Pip Potter <61438964+lmbr-pip@users.noreply.github.com>

Add instructions about null renderer

---

editor.cfg
scriptcanvas/SpawnIfAuthority.scriptcanvas

Addresses https://github.com/o3de/o3de/issues/10031 by using the guidance outlined in https://github.com/o3de/o3de/issues/10031#issuecomment-1159038043. This also fixes a cvar being misnamed in editor.cfg

Add missing spawn ticket ref to SpawnIfAuthority.sc and fix misnamed cfg var

---

Gem/Code/Source/Components/NetworkPlayerMovementComponent.cpp
Gem/Code/Source/Components/NetworkRandomComponent.cpp
Gem/Code/Source/Components/NetworkSimplePlayerCameraComponent.cpp
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp

Updates naming per https://github.com/o3de/o3de/pull/11668

Update IsAuth/Auto naming

---

Levels/SampleBase/SampleBase.prefab
Levels/SpawningPerfTest/SpawningPerfTest.prefab
Prefabs/Test_Net_Object.prefab

- No code changes
- Updated perf level to use physics again
- Removed Selection Component from prefabs

[No code changes] Updated the level to remove SelectionComponent. Updated perf level

---

.gitignore

Signed-off-by: byrcolin <byrcolin@amazon.com>

update the .gitignore to not include .idea .vs and .vscode

---

Gem/Code/Source/MultiplayerSampleModule.cpp

This is a companion change to https://github.com/o3de/o3de/pull/14031 to fix RELEASE builds

Add Client and Server Module declarations for MPS

---

scripts/build/Platform/Linux/build_config.json
scripts/build/Platform/Windows/build_config.json

Add periodic clean daily pipeline to upload daily MPS build artifacts to S3
Signed-off-by: Shirang Jia <shiranj@amazon.com>

Add periodic clean daily tag for MPS

---

Gem/Code/Source/GameState/GameStatePreparingMatch.cpp
Gem/Code/Source/GameState/GameStatePreparingMatch.h
Gem/Code/Source/GameState/GameStateWaitingForPlayers.cpp
Gem/Code/Source/GameState/GameStateWaitingForPlayers.h

Fix linux build
* Build editor and server launcher on Ubuntu
* Ran in editor

Remove unusued member variables to enable Linux build

---

Gem/Code/Source/Components/NetworkPlayerMovementComponent.cpp

Main issue fixed:
- dropping some of the input data that were ignoring all the last press and hold series of inputs between CreateInput calls

Fixed mouse aiming

---

Prefabs/Player.prefab

Also increased the aim distance for hitting targets far away.

Player weapon fires 4 times a second

---

Prefabs/Player.prefab

Pistol attachment and Update to Target Fire Graphic.

---

UICanvases/Reticle.uicanvas
scriptcanvas/ReticleEffects.scriptcanvas

- Inserted a node to check if the local player is autonomous and only then play the reticle effect
- Only minor cleanup for player damaged effect canvas

Reticle flashes only on player who shot (No C++ changes)

---

Levels/NewStarbase/NewStarbase.prefab

Removed the HUD component from the level data, it's a UI component and doesn't belong there.

Removed invalid HUD component.

---

Levels/NewStarbase/NewStarbase.prefab

to fit with traps, redid the lower round area in anticipation of using jump pads to let players jump up, moved teleport exits out of dangerous areas

Added several energy ball traps, updated gem spawn locations 

---

Levels/NewStarbase/NewStarbase.prefab

This adds several malfunctioning shield generator traps to the level and further adjusts/adds gem spawns.

Adding shield gen traps and further adjusting gem spawns

---

Levels/NewStarbase/NewStarbase.prefab

Removing some manual overrides on the starbase level prefab so that changes in the source prefabs work correctly

The removes a lot of instance specific prefab overrides from the starbase level

---

Gem/Code/Source/AutoGen/EnergyCannonComponent.AutoComponent.xml
Gem/Code/Source/Components/Multiplayer/EnergyCannonComponent.cpp
Gem/Code/Source/Components/Multiplayer/EnergyCannonComponent.h
Gem/Code/Source/Effects/GameEffect.cpp
Levels/GameplayTest/GameplayTest.prefab
PopcornFX/Particles/EnergyBallTrap/FX_EnergyBallTrap_BuildUp.pkfx
Prefabs/Energy_Cannon_with_Energy_Ball.prefab

Changes to incorporate the new energy cannon model and line up all its effects.
Requires this dependent PR:
https://github.com/o3de/o3de-multiplayersample-assets/pull/148
https://user-images.githubusercontent.com/82241079/229255858-9725dd97-0ccf-44b1-84ae-aa2fe15879fe.mp4

Energy cannon refinements

---

Gem/Code/Source/Components/Multiplayer/GemSpawnerComponent.cpp
Gem/Code/Source/Components/NetworkMatchComponent.cpp

Fixes https://github.com/o3de/o3de-multiplayersample/issues/303

Fix Linux Build

---

Materials/decal/scorch_01/scorch_01_decal_02_basecolor.png
Materials/decal/scorch_01/scorch_01_decal_02_normal.png
Materials/decal/scorch_01/scorch_01_decal_02_opacity.png
Materials/decal/scorch_01_decal.material

This PR has some tweaked decal textures to try out for the shield generator blast mark

Decal Tweaks

---

Prefabs/PlayerDisconnectScreen.prefab
UICanvases/Disconnected/Disconnected.uicanvas
UICanvases/Disconnected/disconnected_pop_up.png
scriptcanvas/ClientDisconnect.scriptcanvas

When the client disconnects from the server, they will now get the following pop-up for 5 seconds before being returned to the Start Menu:
Note: This PR provides a prefab, the prefab will need to be added to the level in a separate PR to avoid level checkin collisions.

Added client disconnect flow.

---

Documentation/GamplayConfiguration.md
README.md
Registry/multiplayersample.setreg

During recent playtests, a number of players triggered the "win_condition" which was 333
* Hitting this too early in game
* Limited UX to highlight the win condition
PR:
* Raises it to 400 so its harder to hit
* Adds minimal documentation around condition

Ajust win condition to reduce occurency.

---

credit.md

Adding initial contributors list for O3DE 2305, along with special thanks and music credits

First pass of MPS credit.md

---

Levels/NewStarbase/NewStarbase.prefab

Adding several comment components.

Adding comment components to level art entities

---

Gem/Code/Source/Components/BackgroundMusicComponent.cpp
Gem/Code/Source/Components/BackgroundMusicComponent.h
Gem/Code/Source/MultiplayerSampleModule.cpp
Gem/Code/multiplayersample_files.cmake
Levels/NewStarbase/NewStarbase.prefab
Sounds/wwise/1070395499.wem
Sounds/wwise/1073420800.wem
Sounds/wwise/115250578.wem
Sounds/wwise/655023540.wem
Sounds/wwise/MultiplayerSample_SoundBank.bnk
Sounds/wwise_project/Actor-Mixer Hierarchy/AMPS/LVL.wwu
Sounds/wwise_project/Actor-Mixer Hierarchy/AMPS/MX.wwu
Sounds/wwise_project/Events/AMPS/AMB.wwu
Sounds/wwise_project/Events/Default O3DE Work Unit.wwu
Sounds/wwise_project/Originals/SFX/Beauty Flow.wav
Sounds/wwise_project/Originals/SFX/Future Gladiator.wav
Sounds/wwise_project/Originals/SFX/Rocket.wav
Sounds/wwise_project/Originals/SFX/incompetech/Dream Catcher.wav
Sounds/wwise_project/Soundcaster Sessions/Default Work Unit.wwu
libs/gameaudio/wwise/multiplayersample_controls.xml

Adds three new streaming audio pieces composed by the legendary Kevin MacCloud:
- Rocket
- Future Gladiator
- Beauty Flow
Adds a new background music component to the multiplayer sample, and adds that component to the AmbientAudio entity on the level:
The component will loop through the user-defined playlist playing each track after the next in an infinite loop.

Adds background music to the multiplayer sample project

---

README.md

Addresses https://github.com/o3de/o3de-multiplayersample/issues/184

Update README.md to include branch matching information

---

README.md

Add note about LFS setup as its easy to forget.

Update README.md to explicitly mention LFS

---

MPSGameLift/Documentation/GameLift.md
MPSGameLift/Scripts/export_gamelift_server_package.py

Starting an exporter script for Multiplayer Sample GameLift. 
Removed some steps from the Readme
Note: Currently doesn't support Multiplayer Sample built with engine SDK
Future Improvements:
- SDK engine support
- Automatically export zip of exes, dlls, and pak files
- Need automated testing to ensure this script doesn't break

Multiplayer Sample GameLift Exporter Script

---

credits.md

Adding a missing MPS developer.

Updating credits.md

---

Levels/MultiplayerScriptingSample/MultiplayerScriptingSample.prefab
Prefabs/PlayerInScripting.prefab
scriptcanvas/scripting_player_input.scriptcanvas

Updated player controller with AI input generation (the top portion is the AI input portion):
Updated the scripting sample level with a confined space and multiple networked objects and player spawners:
Tested with 25 clients on the same machine as the server, with the server running at 30 fps.
https://user-images.githubusercontent.com/5432499/232544689-f1f9c7d2-efd1-45b4-96eb-e54205f6c271.mp4

Updated the scripting sample for performance tests

---

Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp

This PR needs to work with the PR for O3DE: https://github.com/o3de/o3de/pull/16027

Fullscreen resolution support

---

MPSGameLift/Documentation/GameLift.md
MPSGameLift/README.md

Updates the Multiplayer Sample GameLift documentation to detail the steps to setup more than one server on a single EC2 instance via multiprocess.

Update documentation to describe multi-process setup

---

AssetBundling/SeedLists/BasePopcornFxSeedList.seed
AssetBundling/SeedLists/GameSeedList.seed
AssetBundling/SeedLists/VFXSeedList.seed
Gem/Code/Source/Components/NetworkStressTestComponent.h
Gem/Code/Source/Effects/GameEffect.h

- Expanded seed lists to include all platforms
- Clang compilation fixes for release monolithic launcher builds

Linux release monolithic fixes

---

AssetBundling/SeedLists/GameSeedList.seed
MPSGameLift/Code/Include/MPSGameLift/IMatchmaking.h
MPSGameLift/Code/Source/Components/UI/UiGameLiftFlexMatchConnect.cpp
MPSGameLift/Code/Source/Components/UI/UiGameLiftFlexMatchConnect.h
MPSGameLift/Code/Source/MPSGameLiftModuleInterface.h
MPSGameLift/Code/Source/MatchmakingSystemComponent.cpp
MPSGameLift/Code/Source/MatchmakingSystemComponent.h
MPSGameLift/Code/mpsgamelift_client_files.cmake
MPSGameLift/Prefabs/GameLiftFlexMatchConnect.prefab
MPSGameLift/UICanvases/GameLiftFlexMatchConnect.uicanvas

- Menu allowing players to connect via FlexMatch
- Player can press CONNECT or QUIT
- Simple connection status text added for debug information
- Added menu to the game seed list

FlexMatch Connection Menu

---

MPSGameLift/Code/CMakeLists.txt

Adding missing dependency to MPSGameLift gem

MPSGameLift Gem Compile Fix

---

ExportScripts/export_mps.py
MPSGameLift/Scripts/install.sh

Updating Multiplayer Sample export script to support building headless server. 
Adding install.sh for GameLift Linux servers to install system libraries

GameLift Server Exporter Updates

---

Resources/GameSDK.ico
Resources/LegacyLogoLauncher.bmp

Adding logo to fix compiler error

Adding Logo

---

.gitignore
Docker/Dockerfile
Docker/README.md
Docker/build.sh
Docker/launch.sh

This PR adds Docker support for the o3de-multiplayer sample. The details of the Docker support is contained in the new `README.md` file that is part of this PR.
Tested the Docker build and run steps described in the README.md for the unified launcher.

Docker support for Multiplayer Sample

---

Gem/Code/Source/Components/OcclusionFilteredEntityComponent.cpp

updating multiplayer sample occlusion based entity filter with api changes from occlusion bus on development branch
https://github.com/o3de/o3de/pull/18131

Updated occlusion filter class with occlusion bus api changes

---

InputBindings/player.inputbindings

Gamepad controls: left stick moves player, right-stick moves camera, right trigger shoots gun, start button opens menu
Fixes #488

Player Gamepad Control

---

InputBindings/player.inputbindings

Adding more gamepad options. 
1) Y=jump 
2) Left-trigger = sprint/walk
3) Inverted x-axis

Gamepad Control: Jump and Sprint
