o3de/o3de-multiplayersample

Gem/Code/Source/Components/SimplePlayerCameraComponent.cpp

It looks like unity build might work but non-unity has a compile error. This fixes that.

Camera component build fix

---

Gem/Code/Source/Components/NetworkAnimationComponent.cpp
Gem/Code/Source/Components/NetworkAnimationComponent.h

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?view=msvc-160
```
Using the token operator to compare signed and unsigned numbers required the compiler to convert the signed value to unsigned
```

fix for w4018

---

Gem/Code/Source/MultiplayerSampleModule.cpp
Gem/Code/multiplayersample_files.cmake

Removes references to code not yet in o3de main.

Remove references involving IFilteredEntityManager

---

preview.png

Signed-off-by: nggieber <nggieber@amazon.com>

Replace Lumberyard Beaver preview image with default O3DE image

---

Gem/Code/CMakeLists.txt

This simplifies the `ly_enable_gems` call down to a single call for the MultiplayerSample gem.
Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

Updated the MultiplayerSample `ly_enable_gems` call to remove the deprecated arguments

---

Gem/Code/multiplayersample_autogen_files.cmake

This change corresponds to changes proposed in o3de at https://github.com/o3de/o3de/pull/4321 

Update autogen cmake to accomodate relocated jinja in MP Gem

---

README.md
client.cfg
server.cfg

Note, this change is due to a breaking change that changes where console command files are found when using the following launcher command parameter:
`--console-command-file=server.cfg`

Added server.cfg and client.cfg to the project

---

README.md

Notes cmds to build ServerLauncher target prior to running it. Also fixes a typo in link to `cvar` tutorial.
Signed-off-by: allisaurus <34254888+allisaurus@users.noreply.github.com>

Add server build command to README

---

Gem/Code/CMakeLists.txt

Remove depreciated use of ly_get_list_relative_pal_filename; replaced with o3de_pal_dir
Tested by reconfiguring and building MultiplayerSample on Windows and seeing the warnings go away.

Cmake Update: Remove Depreciated Use of ly_get_list_relative_pal_filename

---

Gem/Code/Source/AutoGen/NetworkWeaponsComponent.AutoComponent.xml
Gem/Code/Source/Components/NetworkWeaponsComponent.cpp
Gem/Code/Source/Weapons/SceneQuery.cpp
Gem/Code/Source/Weapons/WeaponGathers.cpp
Gem/Code/Source/Weapons/WeaponTypes.h

This change addresses a few issues causing desyncs in MultiplayerSample when firing the player's weapon
1. Replicates the start position of the shot as animation bones are not synced making the fire position unreliable
2. When filtering rewindable objects, prevent checking static rigid bodies as they're expected to be stationary so their rewindable frame shouldn't be relevant. This fixes the floor being filtered out of collision logic.
https://github.com/o3de/o3de/pull/7534/files addressed changes in the core around NetworkTime and Rewindables.

Fix various issues leading to desyncs while shooting

---

README.md
editor.cfg

While running through [this tutorial](https://www.o3de.org/docs/learning-guide/tutorials/multiplayer/first-multiplayer-component/) with @AMZN-Gene, discovered local server launch from within the editor wasn't enabled by default. Feels like it should be for this project, so this change adds an `editor.cfg` file with `editorsv_enabled=true` and updates the README accordingly. 
NOTE: the [CVAR](https://www.o3de.org/docs/user-guide/programming/cvars/) link doesn't actually contain any content, so I removed it. (and created [this issue](https://github.com/o3de/o3de.org/issues/1441))
1. Run the editor
2. Type `editorsv_enabled` in the console
3. the output should reflect this value is set to "true"

Add editor.cfg to enable local server from editor

---

Gem/Code/Source/AutoGen/NetworkStressTestComponent.AutoComponent.xml
Gem/Code/Source/Components/NetworkStressTestComponent.cpp
Gem/Code/Source/Components/NetworkStressTestComponent.h

Adding configuration options that allow the stress test to autospawn a number of entities at a given interval without imgui interaction

Adds some simple automation capabilities to the  network stress test component

---

editor.cfg

That resolves the issue with ctrl-g multiplayer experience stuck waiting on the Editor to tick to send the level data to the started server process in the foreground.

Enables Keep Editor Ticking option

---

Gem/Code/Source/AutoGen/NetworkTestSpawnerComponent.AutoComponent.xml
Gem/Code/Source/Components/PerfTest/NetworkRandomImpulseComponent.cpp
Gem/Code/Source/Components/PerfTest/NetworkTestSpawnerComponent.cpp
Levels/SpawningPerfTest/SpawningPerfTest.prefab

"Respawn Enabled", if true will delete old entities, and spawn new ones. Otherwise, will stop spawning once the desired maximum count of instances is reached.

Added a workaround switch to avoid issues with deactivating network entities.

---

scriptcanvas/SpawnIfAuthority.scriptcanvas

Updating to use updated `Spawn` and new `Create Spawn Ticket` Script Canvas nodes, per https://github.com/o3de/o3de/pull/7887
NOTE: removes bad `"m_spawnableAsset"` block highlighted in https://github.com/o3de/o3de/issues/8206
SpawnIfAuthority.scripcanvas graph _before_
SpawnIfAuthority.scripcanvas graph **after**
Screen shot of testing server + client with spawned player

Update spawn nodes in SpawnIfAuthority

---

Gem/Code/enabled_gems.cmake
Registry/assetsprocessor_settings.setreg

Replaced the Atom_AtomBridge dependency with Atom.
Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

Updated the MultiplayerSampleData ScanFolder to use a portable reference to the Atom gem.

---

Levels/SampleBase/SampleBase.prefab
scriptcanvas/SpawnIfAuthority.scriptcanvas

Fix SpawnIfAuthority script canvas so it can open. 
Tested by opening SpawnIfAuthority script canvas and seeing that it can open. Ensure filter.prefab is spawned on server and client, but and client-side filters out the spheres.
Resolves #142 

Fix SpawnIfAuthority Script Canvas

---

Levels/SpawningPerfTest/SpawningPerfTest.prefab

SpawningPerfTest was never updated to have a Player Spawner component. This adds one using one of the gold box entities as the target net spawnable.

Add Player Spawner to perf test level

---

preview.png

Change MPSample project image so it's not the default
Tested by opening o3de.exe (Project Manager) and seeing the new icon
Fixes #160
BEFORE
AFTER

MPSample Project Preview Icon

---

Gem/Code/Source/Components/NetworkSimplePlayerCameraComponent.cpp
Gem/Code/Source/Components/NetworkSimplePlayerCameraComponent.h
Levels/SampleBase/SampleBase.prefab

This removes the FlyCameraComponent from SampleBase's camera. It fights with NetworkSimplePlayerCameraComponent on position causing a lot of jittering on the camera's position. This change also updates NetworkSimplePlayerCameraComponent to use blend factor to interpolate between current and previous aim angles much like NetworkTransformComponent.

Remove FlyCameraComponent and update SimplePlayerCamera interpolation

---

Gem/Code/Source/AutoGen/NetworkStressTestComponent.AutoComponent.xml

Fixing compile error due to bad archetype property, now that archetypes init values are working
Tested by compiling, and making sure the property was properly initialized.

Fixing AutoComponent Compile Error

---

Gem/Code/Source/MultiplayerSampleSystemComponent.cpp
Gem/Code/Source/MultiplayerSampleSystemComponent.h

Adding entity preactivation callback to network spawners in order for multiplayer system to edit the network entities before it's activated (used to turn on autonomous role)
This change depends on an o3de change: https://github.com/o3de/o3de/pull/10951

ClientServer Fix

---

Gem/Code/Source/Spawners/RoundRobinSpawner.cpp

Make sure round robin spawn index is reset after unregistering.
Also added safety net to check for out-of-bounds spawn index if needed
Fixes #193 

Safety Check Round Robin Spawner Index

---

Gem/Code/enabled_gems.cmake

Blast gem is currently not operational since there are no tools to author blast assets and therefore it'll be moved to an experimental branch in o3de-extras (https://github.com/o3de/o3de/pull/13584).
Signed-off-by: moraaar <moraaar@amazon.com>

Disabled Blast gem in MultiplayerSample

---

Levels/MultiplayerScriptingSample/MultiplayerScriptingSample.prefab
Levels/SampleBase/SampleBase.prefab
Levels/SpawningPerfTest/SpawningPerfTest.prefab

**IMPORTANT: Please approve but DO NOT merge this PR yet!** 
@moraaar will merge it once the work in [PhysX_StaticRigidBody_Staging](https://github.com/aws-lumberyard-dev/o3de/tree/PhysX_StaticRigidBody_Staging) branch is in o3de/development.
More information about this update here: https://github.com/o3de/o3de/pull/14261
Steps done:
- Open Editor.
- Run command `ed_physxUpdatePrefabsWithColliderComponents`.
Signed-off-by: moraaar <moraaar@amazon.com>

Updated prefabs to follow new pattern that colliders require a rigid body

---

.gitignore
Gem/Code/Source/Spawners/RoundRobinSpawner.cpp

The make_pair function template is meant for template argument deduction.
If the template arguments are to be specified, then the `AZStd::pair` template should be used directly.
Other changes: Added the CMakeUserPresets.json to the .gitignore
Built the Multiplayer Sample project on Windows using non-unity files

Removed explicit template arguments from `AZStd::make_pair`

---

Gem/Code/multiplayersample_autogen_files.cmake

If the Multiplayer Gem location is ever moved or renamed it would break the autogen references in the project
fixes #44
Configured and built the Multiplayer Sample project successfully

Replacing the non-portable reference to the Multiplayer Gem location with a portable reference

---

Gem/Code/multiplayersample_autogen_files.cmake

Cherry-picking over https://github.com/o3de/o3de-multiplayersample/pull/242/commits/49c4c364d41f1be348592f7f9b5794d018fd7c8b

Replacing the non-portable reference to the Multiplayer Gem location

---

cmake/EngineFinder.cmake

Fixes an issue where Findo3de.cmake would throw this error:
```
-- Selecting engine 'D:/git/o3de-stab-worktree'
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
This engine was not found to be compatible with your project, or no
compatibility checks were done.  For more information, run the command
again with '--log-level VERBOSE'.  (missing: PACKAGE_VERSION_COMPATIBLE)
```
Cmake finds and selects a compatible engine, but there is a case where PACKAGE_VERSION_COMPATIBLE isn't set - this happens when the last engine checked is incompatible. This fix sets PACKAGE_VERSION_COMPATIBLE when a compatible engine is found.
See https://github.com/o3de/o3de/pull/15131 for details.

fix engine not found cmake bug

---

Gem/Code/Source/Components/NetworkPlayerMovementComponent.cpp

Currently, MPS has a bug where a player stops getting movement updates on the server. They can move around locally, but the replicated player stops moving. This logging is a temporary addition to help diagnose whether the input is getting discarded in ProcessInput() or if it's getting discarded somewhere else somehow. It will be removed again once we verify if the problem is occurring in ProcessInput() or somewhere else.

Temp logging to help diagnose movement "disconnect"

---

Gem/Code/Source/Components/NetworkPlayerMovementComponent.cpp
Gem/Code/Source/Components/NetworkSimplePlayerCameraComponent.cpp
Gem/Code/Source/Weapons/BaseWeapon.cpp

Some minor tweaks to the sprint camera to make it less disruptive when running and gunning. This reduces the magnitude of the effect, while only enabling it if the player is actively moving forward. Transition time in and out of the effect is reduced to make it less distracting. Fixes a broken debug cvar in the weapons code that is used to halt simulation when diagnosing hit detection issues.

Sprint cam tweaks

---

Gem/Code/Source/AutoGen/NetworkHealthComponent.AutoComponent.xml
Gem/Code/Source/Components/Multiplayer/PlayerIdentityComponent.cpp
Gem/Code/Source/Components/Multiplayer/PlayerIdentityComponent.h
Levels/GameplayTest/GameplayTest.prefab
PopcornFX/Particles/MalfunctionningShieldGenerator/FX_MalfunctionningShieldGenerator_Explosion.pkfx
Prefabs/Player.prefab
scriptcanvas/DamagePlayer.scriptcanvas
scriptcanvas/ShieldGeneratorExplosionEffects.scriptcanvas
scripts/ShieldGenerator.scriptevents

- Draw the generated player names on the players in the world.
- Removed the debug draw player text.
_Player.prefab and PlayerIdentityComponent.cpp/h_
+ Merge shield changes that were included in the upsteam, but never made it to origin.

Draw Generated Player Names

---

Gem/preview.png
preview.png

Add new preview.png
1. For project manager
2. For gem preview (temporary, expect to replace with something better, but removes Lumberyard beaver icon.
Old icons for reference:
1. Project Manager
2. Gem

Update preview screens

---

Gem/Code/Source/Components/NetworkPlayerMovementComponent.cpp
Gem/Code/Source/Components/NetworkPlayerMovementComponent.h

Makes the shift key toggle player sprint state, rather than require the shift key to be held down to sprint.

Sprint toggle

---

Gem/preview.png
preview.png

* Update project preview so it works better in ProjectManager 
* Text is not perfectly centered, but ok I hope
* Use generic black and white O3DE gem preview icon to match style of other Gem icons in O3DE
Project Preview in Project manager now looks like:
Project name is not obscured by buttons.

Tweak preview icons to work in ProjectManager

---

Gem/Code/Source/Components/Multiplayer/PlayerIdentityComponent.cpp

Making sure to disconnect from the tickbus when the component deactivates. 
Otherwise OnTick can be called with an invalid entity and crash.

PlayerId TickBus Disconnect

---

Gem/Code/Source/AutoGen/GemSpawnerComponent.AutoComponent.xml
Gem/Code/Source/AutoGen/NetworkMatchComponent.AutoComponent.xml
Gem/Code/Source/Components/Multiplayer/GemSpawnerComponent.cpp
Gem/Code/Source/Components/Multiplayer/GemSpawnerComponent.h
Gem/Code/Source/Components/NetworkMatchComponent.cpp
Gem/Code/Source/Components/NetworkTeleportCompatibleComponent.cpp
Levels/NewStarbase/NewStarbase.prefab

When a player dies, they will now spawn a gem cluster where they died worth the same amount that they lose upon death.
Design notes:
* A gem will be spawned from a player's health going to 0, no matter the cause (other player shooting, energy trap, etc).
* The gem will be spawned at the player's position.
* The gem will be worth the exact amount that the dying player loses, or the value set for the gem in the gem table, whichever is higher. (Current configuration sets the gem cluster to 0)
* A gem that is worth 0 will not spawn.
* The gem will despawn at the end of the round if nobody has picked it up.
* The gem will be configured by listing a gem tag on the Network Match component for which gem type to spawn
* The gem tag will be expected to match an entry in the Gem Spawner component in …

Add gem spawning on death

---

Gem/Code/Include/DecalBus.h

Fix for this linux build issue:
```
/data/workspace/o3de/Code/Framework/AzCore/./AzCore/RTTI/BehaviorContext.h:1339:13: error: destructor called on non-final 'MultiplayerSample::SpawnDecalConfig' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
reinterpret_cast<T*>(object)->~T();
```
* Fetched latest `58f5d4253cdcea8c7e223d397f5dd2c1d7f273e0`
* Built
* No build errors
Resolves ﻿﻿https://github.com/o3de/o3de-multiplayersample/issues/303

Add missing virtual destructor required for RTTI

---

scriptcanvas/ShieldGeneratorRoundEffects.scriptcanvas

Updates the shield generator script canvas to use the new entity gather by component node. This fixes the inconsistent damage the shield generator was applying to players when it explodes.

Fixes the damage applied by shield generator explosions

---

Passes/PostProcessParent.pass

This PR is dependent upon https://github.com/o3de/o3de/pull/15645. Once that change goes in this file will need to be updated to reference the correct pass.

Fixing PostProcessParent.pass to reference correct Taa pass.

---

Levels/NewStarbase/NewStarbase.prefab

If the player spawner system finds an empty entry, it will spawn the player using an uninitialized transform. A separate PR will be put up to make that code more robust.

Remove the entry player spawner entry causing players to spawn into space

---

Registry/settings.multiplayersample_gamelauncher.setreg
Registry/settings.multiplayersample_unifiedlauncher.setreg

Small touchup to the checked-in setreg files so that the values end up in the pak builds.
Per the documentation ( https://www.o3de.org/docs/user-guide/settings/issue-az-console-commands/ ), `Amazon/Core/Runtime/ConsoleCommands` and `O3DE/Autoexec/ConsoleCommands` are both used by non-pak builds, but only the latter is processed by the Asset Processor into the bootstrap.game.*.setreg files that are put into the pak builds. 
The previous setreg files worked fine in regular profile builds, but didn't have any effect on settings in pak builds. The new files work for both.
Tested:
* Editor - went into game mode and verified that the Editor launched the ServerLauncher correctly and connected to it.
* Standard profile builds of GameLauncher / ServerLauncher - verified that ServerLauncher worked …

Changed registry keys so that they end up in final pak files.

---

scriptcanvas/ClientDisconnect.scriptcanvas

The MultiplayerSystemComponent has logic that prevents a client from initiating "LoadLevel" at any point after the client has connected to a server for the first time, even if a disconnect occurs. However, the "disconnect" console command will reset the client-side state back to uninitialized, allowing the LoadLevel to succeed. This change to the game's ClientDisconnect state calls "disconnect" explicitly before calling "LoadLevel" so that it can successfully navigate back to the start screen. (Side note - this is why testing the feature with using "disconnect" on the client always worked :( )
This potentially should get fixed in the Multiplayer Gem as well in the development branch, GHI entered here: https://github.com/o3de/o3de/issues/15771 . But since it can't get fixed in the …

Added "disconnect" call to script to reset the multiplayer state to allow LoadLevel to work

---

Gem/Code/Source/Components/UI/UiSettingsComponent.cpp
Gem/Code/Source/Components/UI/UiSettingsComponent.h
Gem/Code/Source/MultiplayerSampleModule.cpp
Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp
Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.h
Gem/Code/multiplayersample_shared_files.cmake

Thanks to some significant help from @lumberyard-employee-dm , this PR adds load/save support to MPS user settings through use of a loose .setreg file. This has been tested with loose file builds as well as pak builds.
Implementation was a little bit tricky due to the user setting of "graphics API", which requires the user settings to get loaded and applied before any system components started up. Thanks to @lumberyard-employee-dm for finding the happy location of the MPS Module constructor to make this work! Thanks also to @lumberyard-employee-dm for providing code to show how to make user settings work with a .setreg file in a secure way that ensures that no engine settings can be directly modified by loading it into its own registry subkey.
One improvement we can make to this code in …

Add persistent user settings support.

---

Levels/GameplayTest/GameplayTest.prefab

The GameplayTest level was nearly unusable because it had the InGameMenu screen always visible. I removed the BasicHUD and InGameMenu screens from the level and replaced it with the UI prefab, which includes both of those, the settings screen, the disconnect screen, and the UI manager.
The InGameMenu now only shows up when pressing Esc or 1, the settings screen works, etc.

Fix UI in GameplayTest.

---

Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp

Fix Linux build issues with latest changes
* Removes registry type warnings of the form
```
/data/workspace/o3de-multiplayersample/Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp:279:23: error: call to member function 'Set' is ambiguous
registry->Set(m_resolutionWidthKey.c_str(), aznumeric_cast<uint64_t>(resolution.first));
~~~~~~~~~~^~~
/data/workspace/o3de/Code/Framework/AzCore/./AzCore/Settings/SettingsRegistry.h:295:22: note: candidate function
virtual bool Set(AZStd::string_view path, bool value) = 0;
^
/data/workspace/o3de/Code/Framework/AzCore/./AzCore/Settings/SettingsRegistry.h:300:22: note: candidate function
virtual bool Set(AZStd::string_view path, s64 value) = 0;
^
/data/workspace/o3de/Code/Framework/AzCore/./AzCore/Settings/SettingsRegistry.h:301:22: note: …
```

Fix Linux type conversion errors

---

.github/dco.yml

What does this PR do?
Activate an additional function in the DCO app to allow reviewers/maintainers to sign-off on behalf of others.
This will also allow contributors who have changed their Github username or email to remediate their own PRs, as the DCO app considers the new email/username as a separate user.
How was this PR tested?
Tested in a forked branch

Add DCO fixup config

---

.github/dco.yml

What does this PR do?
Activate an additional function in the DCO app to allow reviewers/maintainers to sign-off on behalf of others.
This will also allow contributors who have changed their Github username or email to remediate their own PRs, as the DCO app considers the new email/username as a separate user.
How was this PR tested?
Tested in a forked branch

Create dco fixup configuration

---

Documentation/PackedAssetBuilds.md

First rough draft update to the packaging doc guide.
The primary change is making it clear that one needs to use the source engine, not the installer and that one needs to produce both non-monolithic and monolithic engines and project binaries.

Enhanced packaging doc guide

---

MPSGameLift/Code/CMakeLists.txt
MPSGameLift/Scripts/export_gamelift_server_package.py

Adding GameLift runtime dependencies for MPSGameLift so that the GameLift system components are added.
Fixes https://github.com/o3de/o3de/issues/15829
Tested by adding MPSGameLift to project.json gem dependencies, and then running the gamelauncher, serverlauncher, and unifiedlauncher and seeing everything work as normal (not crash)

MPSGameLift: Adding GameLift Runtime Dependencies

---

MPSGameLift/Code/CMakeLists.txt

Change allows unified launcher to act as a GameLift client in order to connect to GameLift server.
Fixes #406 
Tested by connecting Unified Launcher to a GameLift server
Tested by running UnifiedLauncher and ensuring AZ_TRAIT_CLIENT is still 1 and AZ_TRAIT_SERVER is still 1
Tested by running ServerLauncher and ensuring AZ_TRAIT_CLIENT is still 0 and AZ_TRAIT_SERVER is still 1
Tested by running GameLauncher and ensuring AZ_TRAIT_CLIENT is still 1 and AZ_TRAIT_SERVER is still 0

UnifiedLauncher Can Connect to GameLift Server

---

Documentation/PackedAssetBuilds.md

Verified with Windows profile monolithic game build, 23.05 (/main branches of o3de, o3de-multiplayersample, o3de-multiplayersample-assets).

Enhancing bundling docs with command line instructions (AssetBundlerBatch)

---

Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp

Unused variable compile error on release monolithic build.

[Tiny PR] Compile error fix for release mono builds

---

Documentation/PackedAssetBuilds.md
MPSGameLift/Scripts/export_gamelift_server_package.py

MPS GameLift server exporter now produces a release build instead profile
Tested by running exporter to create a GameLift server package -> uploading build to GameLift -> connecting and playing the game.

GameLift Server Exporter Using Release Build Configuration

---

MPSGameLift/Code/Source/Components/UI/UiGameLiftConnectWithPlayerSessionData.cpp
MPSGameLift/Code/Source/Components/UI/UiGameLiftConnectWithPlayerSessionData.h
MPSGameLift/Documentation/GameLift.md
MPSGameLift/UICanvases/GameLiftConnectJson.uicanvas

Fix to properly use the player session data. 
Before this change the menu was using a AWS method to create a new player session... in this case, the developer already has the player session
Fixes #431

Stop Generating 2 Player Sessions

---

ExportScripts/export_standalone_monolithic_windows.py
Registry/assetsprocessor_settings.setreg

This script automates building binaries, processing and bundling assets, and preparing a release directory layout for MPS. Currently it has been designed and tested for windows. A Linux compatible update will be for a future PR.
The script closely matches the instructions described here: https://github.com/o3de/o3de-multiplayersample/blob/development/Documentation/PackedAssetBuilds.md
The arguments for this script are as follows:
```
--project-path
required=True, Path to the intended O3DE project.
--engine-path
required=True, Path to the intended O3DE engine copy.
--output-path
required=True, Path that describes the final resulting Release Directory path location.
--config
default='profile', choices=['release', 'profile'], The CMake build configuration to use when building project …
```

Created new MPS standalone export script for windows

---

AssetBundling/SeedLists/GameSeedList.seed
Documentation/PackedAssetBuilds.md
MPSGameLift/Documentation/GameLift.md
MPSGameLift/Scripts/export_gamelift_server_package.py

- Updating GameLift exporter with --package-gamelauncher option to create a new game client package in a folder called 'MultiplayerSampleGamePackage'
- Adding missing asset seed for Multiplayer Sample client release builds 
- Updating GameLift ReadMe.md to include new client packaging

Game Lift Package Exporter Packages Game Client

---

ExportScripts/export_standalone_monolithic_windows.py

This PR is for addressing feedback left at the end of the previous PR: https://github.com/o3de/o3de-multiplayersample/pull/433
This PR also includes a fix for the following issue: https://github.com/o3de/o3de-multiplayersample/issues/438
The export script has now been tested with the development branch and main branch of o3de and o3de-multiplayer-sample on windows.
The script is able to create a release bundle ready for play using both the release and profile configurations.
This PR does not address adding a testing/validation layer for the script, nor the ability to swap to project-centric  mode. That will be included in a future PR. This is just to fix issues with the existing script.
This script is also only tested for windows. There will be a dedicated PR for updating the script to be …

Mps export feedback patch

---

ExportScripts/export_standalone_monolithic.py
ExportScripts/export_standalone_monolithic_windows.py

This PR introduces the necessary changes for the MPS export script to work cross platform. With these changes, the export script works on both Linux and Windows.
This was tested on both Windows 10 and Linux machines using the development branch of o3de and o3de-multiplayersample. Both successfully exported MPS project with server and game launchers and I was able to run them using instructions found here: https://github.com/o3de/o3de-multiplayersample/blob/development/Documentation/PackedAssetBuilds.md#run-the-final-build-to-verify-it

Cross platform export script

---

scriptcanvas/scripting_player_input.scriptcanvas

These changes were used to verify that a high-end server can support 25 clients at 30 fps.
Changes:
- removed debug text nodes as they were not supported on the server
- gated important text with a check to see if the logic is running on a client

Updated scripts for easier testing of multiple clients on a test level

---

.gitignore
CMakePresets.json
project.json

Minor updates to project related files to better support VS Code
- Add *.code-workspace to gitignore to support multi-root workspaces (project-central)
- Add new CMakePresets.json (which is now in the create project template) to enable presets to work
- Add missing 'engine_version' project.json entry

Project-related updates for Multiplayer sample

---

Documentation/O3DEMPSProjectExportTesting.md

This PR adds instructions for testing out the Project Export feature for MPS, and the expected path from fresh install to fully running the game.
This document is intended for testers to validate if the feature works, or otherwise highlight issues they encountered.

adding instructions to test the project export feature for MPS

---

Documentation/O3DEMPSProjectExportTesting.md

Small change to remove unnecessary `git lfs pull` step from project export instruction doc.

remove lfs instruction from documentation

---

Documentation/O3DEMPSProjectExportTesting.md

Updating the MPS export instructions to use the new O3DE exporter as found here: https://github.com/o3de/o3de/pull/16406

updating MPS export instructions to use official O3DE exporter

---

MPSGameLift/Code/CMakeLists.txt
MPSGameLift/Code/Include/MPSGameLift/IMatchmaking.h
MPSGameLift/Code/Include/MPSGameLift/IRegionalLatencyFinder.h
MPSGameLift/Code/Source/MPSGameLiftModuleInterface.h
MPSGameLift/Code/Source/MatchmakingSystemComponent.cpp
MPSGameLift/Code/Source/MatchmakingSystemComponent.h
MPSGameLift/Code/Source/Tools/MPSGameLiftEditorModule.cpp
MPSGameLift/Code/mpsgamelift_api_files.cmake
MPSGameLift/Code/mpsgamelift_client_files.cmake

Client can request matchmaking from a server-less backend and receives a ticket-id response
Note: JSON parser is crashing when hitting arrays or dictionaries if they are ignored, for that reason, player data is being stored even though we only need the ticket-id.

Client Request Matchmaking

---

.gitignore
Documentation/O3DEMPSProjectExportTesting.md

Fixed example export command to use the `O3DE_PROJECT_PATH` variable in the documentation. Also added entries in the gitignore for the asset lists and bundles, which are generated from the packaging/export script, so that they don't show up as untracked files in git.

Fixed export project example command in documentation

---

Gem/Code/CMakeLists.txt

This is part of the fix for audio not working in the MultiplayerSample unified launcher. The unified target now properly relies on the `AudioSystem.API`.
The other part of this fix is in the O3DE repo to add the proper aliases in the audio gems so they can be depended on in the unified launcher: https://github.com/o3de/o3de/pull/16565

Fixed audio not working in unified launcher

---

Levels/PopcornFxTest/PopcornFxTest.prefab
PopcornFX/PopcornProject.pkproj

Upgrading PopcornFx assets from 2.17.2 to 2.17.3]
Created a new level _PopcornFxTest_ for devs to quickly open and enable all of the particle fx to see if they are working.
Relates to: https://github.com/o3de/o3de-multiplayersample-assets/pull/164
Note: The package file changed, but individual fx files were already up-to-date

Upgrade Popcorn Fx Assets to 2.17.3

---

MPSGameLift/Scripts/install.sh

Cleaned up GameLift install.sh to install Amazon Linux 2023 runtime libraries using built in Linux library package system instead of installing everything from scratch.
Also eliminate the need to copy system ./lib64/ files into the GameLift server exported package.

 GameLift Install.sh Cleanup

---

Levels/NewStarbase/NewStarbase.prefab

Removing terrain gradient until crash issue is fixed (https://github.com/o3de/o3de/issues/17255)
Tested by opening NewStarbase in level editor and seeing the editor no longer crashes.

Removing Terrain Gradient Until Crash Fixed

---

Levels/NewStarbase/NewStarbase.prefab

[Editor image gradient crash has been fixed](https://github.com/o3de/o3de/pull/17422), so reenable terrain in Multiplayer Sample NewstarBase

Re-Enable Terrain

---

ExportScripts/export_mps.py
Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp

Fixes the following build errors when building against the latest o3de development (commit f35b02e8dc78084eae621ff9cea898daa493e553)
```
In file included from /data/workspace/o3de-multiplayersample/build/tools/External/Gem-f6f5d0f3/Code/CMakeFiles/MultiplayerSample.dir/Unity/unity_0_cxx.cxx:5:
/data/workspace/o3de-multiplayersample/Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp:264:32: error: no member named 'm_rayTracing' in 'AZ::Render::SSROptions'
ssrOptions.m_rayTracing = (reflectionType == SpecularReflections::ScreenSpaceAndRaytracing) ? 
~~~~~~~~~~ ^
```
Also fixes the following python error during the project export script
```
File "/data/workspace/o3de-multiplayersample/ExportScripts/export_mps.py", line 248, in <module>
export_multiplayer_sample(ctx=o3de_context, …
```

Fix compile and python errors from the export script

---

Gem/Code/Source/Components/OcclusionFilteredEntityComponent.cpp
Gem/Code/Source/Components/OcclusionFilteredEntityComponent.h
Gem/Code/Source/MultiplayerSampleModule.cpp
Gem/Code/multiplayersample_files.cmake

This is another example of a multiplayer entity filtering component that should prevent network replication for players or objects that cannot be seen by the client, if there is an active occlusion culling system that utilizes the occlusion request bus.
The code compiles in the component can be added from the editor but it is not added or active by default.

Alternate example of multiplier sample entity filtering component using occlusion culling bus

---

Gem/Code/Source/UserSettings/MultiplayerSampleUserSettings.cpp

Multiplayer sample was failing to compile because of an error caused by a warning about a deprecated function call.

Removing deprecated function call from multiplayer sample settings

---

InputBindings/player.inputbindings

Gamepad controls: left stick moves player, right-stick moves camera, right trigger shoots gun, start button opens menu
Fixes #488 
Note: Could not cherry-pick the [2409 gamepad pull request](https://github.com/o3de/o3de-multiplayersample/pull/489) because the player input xml's are incompatible

Gamepad Support

---

MPSGameLift/gem.json

Adding AWS gems as dependency for MPSGameLift gem. 
Fixes compiler error
```
CMake Error at D:/prj/o3de/cmake/LYWrappers.cmake:561 (target_link_libraries):
Target "MPSGameLift" links to:
Gem::AWSClientAuth.Static
but the target was not found.
```

Fix AWS Compiler Error
